
    eureka:
      instance:
        prefer-ip-address: true
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka

    server:
      port: 8001

    spring:
      data:
        mongodb:
          uri: mongodb://localhost:27017
          database: microservice1
      application:
        name: USER-SERVICE
